version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/setup/windows/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/setup/linux"
    schedule:
      interval: "daily"
